module.exports = {
	preconditions: {
		loggedOut: 'I am logged out',
		loggedIn: 'I am logged in as {user}',
	},
	actions: {
		logout: 'I log out',
		login: 'I log in as {user}',
		navigate: 'I navigate to {page}',
		click: 'I click {element}',
		set: 'I set {element} to {string}',
		waitUntilHidden: 'I wait for {element} to disappear',
		wait: 'I wait {float} seconds',
		pause: 'I pause',
		debug: 'I debug',
	},
	assertions: {
		isOnPage: 'I should be on {page}',
		isNotOnPage: 'I should not be on {page}',
		isVisible: '{element} should be visible',
		isNotVisible: '{element} should not be visible',
		hasCount: '{element} should have {int} occurrences',
		hasText: '{element} should be {string}',
		hasTextTable: 'elements should be:',
		hasValue: '{element} should be set to {string}',
		doesNotHaveText: '{element} should not be {string}',
		containsText: '{element} should contain {string}',
		containsTextTable: 'elements should contain:',
		doesNotContainText: '{element} should not contain {string}',
	},
}
